### ISSUE TITLE
Install conflict for qtchooser

### ISSUE THREAD

**Issue by decon4** [sailfishos-chum/qt6#7]
Steps to reproduce:
1. Install SailfishSDK-3.11.1-linux64-online.run (I installed on linux mint 22 Cinnamon)
2. clone supersonik app
git clone https://github.com/piggz/supersonik.git
3. cd supersonik; mkdir build; cd build
4. Setup build tools:
sfdk config target=SailfishOS-4.6.0.13-aarch64
sfdk tools target exec SailfishOS-4.6.0.13-aarch64 ssu ar qt6obs https://repo.sailfishos.org/obs/home:/rinigus:/qt6/sailfish_latest_aarch64/
sfdk tools target exec SailfishOS-4.6.0.13-aarch64 ssu ur
sfdk tools target exec SailfishOS-4.6.0.13-aarch64 zypper ref 
5. Build app:
sfdk build ..

Result:
When building it detects several packages that needs to be installed.
Eventually it will fail on install conflict. Build log is attached.

> Detected 1 file conflict:
>
>File /usr/bin/qmake
>  from install of
>     qt6-qtbase-devel-6.7.2+dev1+main.20240929091800.2.ge2b0b69-1.1.1.jolla.aarch64 (qt6obs)
>  conflicts with file from package
>     qtchooser-26-1.6.3.jolla.aarch64 (@System)
>
>File conflicts happen when two packages attempt to install files with the same name but different contents. If you continue, >conflicting files will be replaced losing the previous content.
>Continue? [yes/no] (no): no
>
>Problem occurred during or after installation or removal of packages:
>Installation has been aborted as directed.
>History:
> - ABORT request:

**Comment by decon4** [comment]
SDK was installed for virtualbox.

**Comment by piggz** [comment]
Thanks for the report, we already have an issue logged at https://github.com/sailfishos-chum/qt6/issues/3
